# Generated by Django 5.0.3 on 2024-03-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.IntegerField(choices=[(1, 'likes'), (-1, 'dislikes'), (0, 'No Reaction')], default=0),
        ),
    ]
